openapi: 3.0.0
info:
  version: 1.0.0-0
  title: books api
  description: api for books

servers:
  - url: /auth0

security:
  - bearerAuth: []

paths:
  /login:
    post:
      description: "login an auth0 user"
      operationId: "Authenticate"
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth0LoginRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth0LoginResponse'
        '405':
          description: Invalid input

  /book/{bookId}:
    get:
      description: "get a book by id"
      operationId: "get Book"
      parameters:
        - $ref: '#/components/parameters/bookIdParam'
      tags:
        - Books
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponse'
        '405':
          description: Invalid input

components:
  parameters:
    bookIdParam:
      in: path
      name: bookId
      required: true
      schema:
        type: string

  schemas:
    Auth0LoginRequest:
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    Auth0LoginResponse:
      properties:
        jwtToken:
          type: string

    BookResponse:
      type: object
      properties:
        title:
          type: string
        author:
          $ref: '#/components/schemas/AuthorResponse'
        averageRating:
          type: string
        isbn:
          type: string
        isbn13:
          type: string
        language_code:
          type: string
        num_pages:
          type: string
        ratings_count:
          type: string
        text_reviews_count:
          type: string
        publication_date:
          type: string
          format: date
        publisher:
          $ref: '#/components/schemas/PublisherResponse'


    AuthorResponse:
      type: object
      properties:
        authorName:
          type: string

    PublisherResponse:
      type: object
      properties:
        publisherName:
          type: string
