server:
    port: 8080

#logging:
#    level:
#      root: DEBUG

auth0:
    domain: dev-xs1u5mnzrm83ke4o.us.auth0.com
    client_id: 0CM2y9a5ym9uE20hQvNp2ALr5lpRLr0E
    client_secret: 3ohzRndl_YUjv9jqucHGBiyXu_ek3dH52CAur4aRHhXK8UL0cx5y8WXH96IjBnlf
    audience: https://books/api
    issuer:  https://dev-xs1u5mnzrm83ke4o.us.auth0.com/

spring:
    datasource:
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/books
    security:
        oauth2:
            client:
                registration:
                    auth0:
                        client-id: ${auth0.client_id}
                        client-secret: ${auth0.client_secret}
                        scope:
                        - openid
                        - profile
                        - email
                provider:
                    auth0:
                        issuer-uri: ${auth0.issuer}
    flyway:
        placeholders:
          application-user: books
        url: jdbc:postgresql://localhost:5432/books
        user: admin
        password: admin
        out-of-order: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
#        hibernate:
#            ddl-auto: update
#        show-sql: true


springdoc:
    version: '@springdoc.version@'
