spring:
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  flyway:
    placeholders:
      application-user: books
    url: jdbc:h2:mem:localdb
    user: sa
    password: password
    out-of-order: true