### auth0 system token
POST https://dev-xs1u5mnzrm83ke4o.us.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type":"client_credentials",
    "client_id":"0CM2y9a5ym9uE20hQvNp2ALr5lpRLr0E",
    "client_secret":"3ohzRndl_YUjv9jqucHGBiyXu_ek3dH52CAur4aRHhXK8UL0cx5y8WXH96IjBnlf",
    "audience":"https://books/api"
}

> {%
 client.global.set("accessToken", response.body.accessToken)
 %}


### admin user token
POST https://dev-xs1u5mnzrm83ke4o.us.auth0.com/oauth/token
Content-Type: application/json

{
  "grant_type":"password",
  "username":"thomas-hiemstra@hotmail.com",
  "password": "Admin@123",
  "audience":"https://books/api",
  "client_id":"0CM2y9a5ym9uE20hQvNp2ALr5lpRLr0E",
  "client_secret":"3ohzRndl_YUjv9jqucHGBiyXu_ek3dH52CAur4aRHhXK8UL0cx5y8WXH96IjBnlf"
}

> {%
 client.global.set("accessToken", response.body.access_token)
 %}


### general user token
POST https://dev-xs1u5mnzrm83ke4o.us.auth0.com/oauth/token
Content-Type: application/json

{
  "grant_type":"password",
  "username":"thomashiemstra16@gmail.com",
  "password": "User@123",
  "audience":"https://books/api",
  "client_id":"0CM2y9a5ym9uE20hQvNp2ALr5lpRLr0E",
  "client_secret":"3ohzRndl_YUjv9jqucHGBiyXu_ek3dH52CAur4aRHhXK8UL0cx5y8WXH96IjBnlf"
}

> {%
 client.global.set("accessToken", response.body.access_token)
 %}


### get USer
GET https://dev-xs1u5mnzrm83ke4o.us.auth0.com/api/v2/642de1ff3595d0580ee31663

### login via api
POST {{host}}/auth0/login
Content-Type: application/json

{
  "username":"thomashiemstra16@gmail.com",
  "password": "User@123"
}

> {%
 client.global.set("accessToken", response.body.jwtToken)
 %}

### simple get
GET {{host}}/home
Authorization: Bearer {{accessToken}}


### book get
GET {{host}}/book/1
Authorization: Bearer {{accessToken}}

### simple get
POST {{host}}/whatever
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username":"thomashiemstra16@gmail.com",
  "password": "User@123"
}

### simple admin get
GET {{host}}/admin
Authorization: Bearer {{accessToken}}

### add Book
POST {{host}}/saveBook
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Some book",
  "author": {
    "id": 1,
    "authorName": "J.K. Rowling"
  },
  "averageRating": "4.57",
  "isbn": "0439785960",
  "isbn13": "9780439785969",
  "language_code": "eng",
  "num_pages": "1",
  "ratings_count": "1",
  "text_reviews_count": "1",
  "publication_date": "2006-09-16",
  "publisher": {
    "id": 1,
    "publisherName": "Scholastic Inc."
  }
}


### add favourite book
POST {{host}}/addFavouriteBook
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": 200
}

### remove favourite book
POST {{host}}/removeFavouriteBook
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": 1
}

### get Favourite books
GET {{host}}/getFavouriteBooks
Authorization: Bearer {{accessToken}}