version: '3.8'
services:
  database:
    image: "postgres:15.2"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
#      POSTGRES_DB: "books"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
      - "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
#  book-app:
#    build:
#      dockerfile: DockerFile
#    restart: always
#    depends_on:
#     - database
#    ports:
#      - "8080:8080"